### ISSUE TITLE
Version has not been replaced

### ISSUE THREAD

**Issue by Kagamine** [myget/BuildTools#7]
https://www.myget.org/gallery/codecomb

![image](https://cloud.githubusercontent.com/assets/2216750/10358781/6b436226-6dc4-11e5-9c9e-a66fcd67d762.png)

![image](https://cloud.githubusercontent.com/assets/2216750/10358789/7df4db2a-6dc4-11e5-86b7-b9ecb9b94774.png)

/cc @maartenba, @xavierdecoster

**Comment by maartenba** [comment]
What does your .nuspec look like?

**Comment by Kagamine** [comment]
I don't have .nuspec file, i just using the sake to compile, like this https://github.com/CodeComb/Localization/

**Comment by maartenba** [comment]
Then Sake/KoreBuild is taking care of versioning. MyGet currently does not support overriding this out of the box.

In your `build.cmd` you may want to add this to override KoreBuild's default version number:
```set DNX_BUILD_VERSION=%PackageVersion%```

**Comment by Kagamine** [comment]
Thanks
